trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    npx prisma generate
    npm run build
  displayName: 'Install and Build'

# This zips the build output so the Release pipeline can move it
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/QASCO_Artifacts.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'