BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[AuditTrail] DROP CONSTRAINT [AuditTrail_createdOn_df];
ALTER TABLE [dbo].[AuditTrail] ADD CONSTRAINT [AuditTrail_createdOn_df] DEFAULT TODATETIMEOFFSET(SYSUTCDATETIME(), '+08:00') FOR [createdOn];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
