import Escalation from "@/lib/escalation";

const escations : Escalation[] = [
  { id: "1001", name: "Alice Johnson", email: "alice.johnson@example.com", project: "Project Alpha", status: "Active" },
  { id: "1002", name: "Bob Smith", email: "bob.smith@example.com", project: "Project Beta", status: "Inactive" },
  { id: "1003", name: "Carol Davis", email: "carol.davis@example.com", project: "Project Gamma", status: "Active" },
  { id: "1004", name: "David Wilson", email: "david.wilson@example.com", project: "Project Delta", status: "Active" },
  { id: "1005", name: "Emma Brown", email: "emma.brown@example.com", project: "Project Omega", status: "Inactive" },
  { id: "1006", name: "Frank Miller", email: "frank.miller@example.com", project: "Project Alpha", status: "Active" },
  { id: "1007", name: "Grace Lee", email: "grace.lee@example.com", project: "Project Beta", status: "Active" },
  { id: "1008", name: "Henry Clark", email: "henry.clark@example.com", project: "Project Gamma", status: "Inactive" },
  { id: "1009", name: "Ivy Lewis", email: "ivy.lewis@example.com", project: "Project Delta", status: "Active" },
  { id: "1010", name: "Jack Walker", email: "jack.walker@example.com", project: "Project Omega", status: "Active" },
  { id: "1011", name: "Karen Hall", email: "karen.hall@example.com", project: "Project Alpha", status: "Inactive" },
  { id: "1012", name: "Liam Allen", email: "liam.allen@example.com", project: "Project Beta", status: "Active" },
  { id: "1013", name: "Mia Young", email: "mia.young@example.com", project: "Project Gamma", status: "Active" },
  { id: "1014", name: "Noah King", email: "noah.king@example.com", project: "Project Delta", status: "Inactive" },
  { id: "1015", name: "Olivia Scott", email: "olivia.scott@example.com", project: "Project Omega", status: "Active" },
  { id: "1016", name: "Paul Green", email: "paul.green@example.com", project: "Project Alpha", status: "Active" },
  { id: "1017", name: "Quinn Adams", email: "quinn.adams@example.com", project: "Project Beta", status: "Inactive" },
  { id: "1018", name: "Ruby Baker", email: "ruby.baker@example.com", project: "Project Gamma", status: "Active" },
  { id: "1019", name: "Sam Carter", email: "sam.carter@example.com", project: "Project Delta", status: "Active" },
  { id: "1020", name: "Tina Evans", email: "tina.evans@example.com", project: "Project Omega", status: "Inactive" },
  { id: "1021", name: "Uma Foster", email: "uma.foster@example.com", project: "Project Alpha", status: "Active" },
  { id: "1022", name: "Victor Gray", email: "victor.gray@example.com", project: "Project Beta", status: "Active" },
  { id: "1023", name: "Wendy Hughes", email: "wendy.hughes@example.com", project: "Project Gamma", status: "Inactive" },
  { id: "1024", name: "Xavier James", email: "xavier.james@example.com", project: "Project Delta", status: "Active" },
  { id: "1025", name: "Yara Kelly", email: "yara.kelly@example.com", project: "Project Omega", status: "Active" },
  { id: "1026", name: "Zane Lopez", email: "zane.lopez@example.com", project: "Project Alpha", status: "Inactive" },
  { id: "1027", name: "Aaron Martinez", email: "aaron.martinez@example.com", project: "Project Beta", status: "Active" },
  { id: "1028", name: "Bella Nelson", email: "bella.nelson@example.com", project: "Project Gamma", status: "Active" },
  { id: "1029", name: "Caleb Ortiz", email: "caleb.ortiz@example.com", project: "Project Delta", status: "Inactive" },
  { id: "1030", name: "Diana Perez", email: "diana.perez@example.com", project: "Project Omega", status: "Active" },
  { id: "1031", name: "Ethan Quinn", email: "ethan.quinn@example.com", project: "Project Alpha", status: "Active" },
  { id: "1032", name: "Faith Rivera", email: "faith.rivera@example.com", project: "Project Beta", status: "Inactive" },
  { id: "1033", name: "Gavin Sanders", email: "gavin.sanders@example.com", project: "Project Gamma", status: "Active" },
  { id: "1034", name: "Holly Turner", email: "holly.turner@example.com", project: "Project Delta", status: "Active" },
  { id: "1035", name: "Ian Underwood", email: "ian.underwood@example.com", project: "Project Omega", status: "Inactive" },
  { id: "1036", name: "Jade Vasquez", email: "jade.vasquez@example.com", project: "Project Alpha", status: "Active" },
  { id: "1037", name: "Kyle White", email: "kyle.white@example.com", project: "Project Beta", status: "Active" },
  { id: "1038", name: "Lara Xu", email: "lara.xu@example.com", project: "Project Gamma", status: "Inactive" },
  { id: "1039", name: "Mason Young", email: "mason.young@example.com", project: "Project Delta", status: "Active" },
  { id: "1040", name: "Nina Zane", email: "nina.zane@example.com", project: "Project Omega", status: "Active" },
  { id: "1041", name: "Oscar Allen", email: "oscar.allen@example.com", project: "Project Alpha", status: "Inactive" },
  { id: "1042", name: "Paula Brooks", email: "paula.brooks@example.com", project: "Project Beta", status: "Active" },
  { id: "1043", name: "Quincy Clark", email: "quincy.clark@example.com", project: "Project Gamma", status: "Active" },
  { id: "1044", name: "Rita Diaz", email: "rita.diaz@example.com", project: "Project Delta", status: "Inactive" },
  { id: "1045", name: "Steve Edwards", email: "steve.edwards@example.com", project: "Project Omega", status: "Active" },
  { id: "1046", name: "Tara Flores", email: "tara.flores@example.com", project: "Project Alpha", status: "Active" },
  { id: "1047", name: "Ulysses Grant", email: "ulysses.grant@example.com", project: "Project Beta", status: "Inactive" },
  { id: "1048", name: "Vera Harris", email: "vera.harris@example.com", project: "Project Gamma", status: "Active" },
  { id: "1049", name: "Will Irving", email: "will.irving@example.com", project: "Project Delta", status: "Active" },
  { id: "1050", name: "Xena Johnson", email: "xena.johnson@example.com", project: "Project Omega", status: "Inactive" }
]

export default escations