import Project from "@/lib/project";

const projects : Project[] = [
  { id: "1001", code: "IT", name: "Information Technology", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1002", code: "IAD", name: "Internal Audit Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1003", code: "IAD-DPMC", name: "Internal Audit Department-DPMC", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1004", code: "SPR", name: "Siena Park Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1005", code: "Treasury", name: "Treasury Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1006", code: "HRD", name: "Human Resources", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "4th escalation", status: "Active" },
  { id: "1007", code: "ACP", name: "Accolade Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1008", code: "DPMCOPs", name: "DPMC Operations", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1009", code: "ASR", name: "Asteria Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1010", code: "CONS", name: "Construction", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1011", code: "RWP", name: "Rosewood Pointe", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1012", code: "SRT", name: "Sheridan Towers", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1013", code: "LEGAL", name: "Legal Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1014", code: "ASR-PDI", name: "Asteria Residences - PDI", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on PDI Parking Slots", status: "Active" },
  { id: "1015", code: "EOM-PDI", name: "East Ortigas Mansion-PDI", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Parking Slots", status: "Active" },
  { id: "1016", code: "MAV", name: "Maricielo Villas", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit of PCF, Collection, Other Income & Communi...", status: "Active" },
  { id: "1018", code: "PURCHASING", name: "Purchasing Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "AUDIT ON PURCHASING", status: "Active" },
  { id: "1019", code: "MPR", name: "Mayfield Park Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1020", code: "LMR", name: "Lumiere Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1021", code: "LEV", name: "Levina Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit of PCF, Collection, Other Income & Communi...", status: "Active" },
  { id: "1022", code: "RPR", name: "Royal Palm Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1023", code: "VWR", name: "Verawood Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Special Audit", status: "Active" },
  { id: "1024", code: "BWD", name: "The Birchwood Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1025", code: "DMCI - RMC", name: "DMCI - Ready Mixed Concrete", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Special Audit", status: "Active" },
  { id: "1026", code: "HRD-ATR", name: "Human Resources & The Ath...", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Timekeeping and Labor Cost", status: "Active" },
  { id: "1027", code: "ZNT", name: "Zinnia Towers", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1028", code: "VWR - Reg", name: "Verawood Residences - Reg", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1029", code: "DICD", name: "Documents Inventory Control ...", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1030", code: "LVR", name: "La Verti Residence", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1031", code: "AVB", name: "Alta Vista de Boracay", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1032", code: "EOM", name: "East Ortigas Mansion", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1033", code: "PUCHASIN", name: "Purchasing Department-DPMC", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1034", code: "DPMC PURCH", name: "Purchasing DPMC", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1035", code: "ADU", name: "Asset Disposal Unit", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1036", code: "CASHIERING", name: "Cashiering", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1037", code: "CSHR PDC", name: "Treasury - Cashiering", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1038", code: "TAM", name: "The Analysis", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1039", code: "TGR", name: "Tivoli Garden Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1040", code: "FIN", name: "Finance Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1041", code: "LSD", name: "Leasing Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1042", code: "OCP", name: "One Castilla Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1043", code: "JOMSAR", name: "JOMSAR Construction & Dev...", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1044", code: "TRW", name: "The Redwoods", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1045", code: "MAP", name: "Magnolia Place Condominium", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1046", code: "OPR", name: "Ohana Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1047", code: "MPP", name: "Arista Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1048", code: "ARP", name: "Stellar Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1049", code: "SLP", name: "Raya Garden Condominium", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1050", code: "RGC", name: "Fairway Terraces", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1051", code: "FWT", name: "DMCI Homes - Davao", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1052", code: "DVO", name: "DMCI Homes - Head Office", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1053", code: "DHCC", name: "Brio Tower", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Special Project", status: "Active" },
  { id: "1054", code: "BRT", name: "Cypress Tower", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1055", code: "CYP", name: "General Service Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1056", code: "GSD", name: "Riverfront Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1057", code: "RFR", name: "Cedar Crest", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1058", code: "CEC", name: "Sorrel Residences Condominium", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1059", code: "SOR", name: "Asset Management Group", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Regular Audit", status: "Active" },
  { id: "1060", code: "MIR", name: "Verdon Parc", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1061", code: "AMG", name: "Zenith Mobility Solutions Servi...", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1062", code: "VER", name: "Alea Residences", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Collection and Other Income - ALR", status: "Active" },
  { id: "1063", code: "ZEP", name: "AREA 3", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1064", code: "ALR", name: "Head Office - Timekeeping", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Timekeeping of Head Office-based empl...", status: "Active" },
  { id: "1065", code: "AREA 3", name: "AREA 5", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Timekeeping of Area 1", status: "Active" },
  { id: "1066", code: "HOF", name: "HUMAN RESOURCE", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Gov't. Mandatories and Emergency Cash Advances", status: "Active" },
  { id: "1067", code: "AREA 1", name: "Legal & Permits", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Permits Application", status: "Active" },
  { id: "1068", code: "AREA 5", name: "AREA 1 Community Events", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit of Community Events - Area 1", status: "Active" },
  { id: "1069", code: "HRD-BEN", name: "Torre De Manila", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1070", code: "Permits", name: "Dansalan Gardens", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Collection and Other Income", status: "Active" },
  { id: "1071", code: "AREA 1_CE", name: "Flair Towers", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Collection and Other Income", status: "Active" },
  { id: "1072", code: "TDM", name: "Design and Engineering", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit of Subcontracting Process", status: "Active" },
  { id: "1073", code: "DG", name: "Marketing Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Marketing Materials and CSR Activities Audit", status: "Active" },
  { id: "1074", code: "DT", name: "Accounting Department", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1075", code: "MKTNG", name: "AREA 6", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Collection and Other Income", status: "Active" },
  { id: "1076", code: "ACCTNG", name: "Calathea Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Collection and Other Income", status: "Active" },
  { id: "1077", code: "AREA 6", name: "AREA 6", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: undefined, status: "Active" },
  { id: "1078", code: "CLP", name: "Calathea Place", company: "DMCI PROJECT DEVELOPERS, INC.", remarks: "Audit on Collection and Other Income", status: "Active" }
]

export default projects